# This is a basic workflow to help you get started with Actions

name: first_msg_echo

# Controls when the workflow will run
on:
  [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
    - name: Print message
      run: echo "Hello World!"
